name: Auto EUserv

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-week:
    runs-on: ubuntu-latest
    outputs:
      last_week: ${{ steps.check_last_week.outputs.last_week }}
    steps:
      - name: Check if it is the last week of the month
        id: check_last_week
        run: |
          DAY=$(date +'%d')
          LAST_DAY=$(date -d "$(date +'%Y-%m-01') +1 month -1 day" +'%d')
          START_LAST_WEEK=$((LAST_DAY - 6))
          if [ "$DAY" -ge "$START_LAST_WEEK" ]; then
            echo "It is the last week of the month."
            echo "::set-output name=last_week::true"
          else
            echo "It is not the last week of the month."
            echo "::set-output name=last_week::false"
          fi

  run-script:
    needs: check-week
    if: needs.check-week.outputs.last_week == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify Python3.x

      - name: Install dependencies
        run: |
          pip install beautifulsoup4==4.12.3 certifi==2024.2.2 charset-normalizer==3.3.2 et-xmlfile==1.1.0 idna==3.7 numpy==1.26.4 openpyxl==3.1.2 pandas==2.2.2 python-dateutil==2.9.0.post0 pytz==2024.1 requests==2.32.2 six==1.16.0 soupsieve==2.5 tzdata==2024.1 urllib3==2.2.1

      - name: Run script
        if: needs.check-week.outputs.last_week == 'true'
        env:
          EUSERV_USERNAME: ${{ secrets.EUSERV_USERNAME }}
          EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
          TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
          TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}
        run: python Github_Action.py
